---
title: "Day 2"
pagetitle: "Mise en Place"
output:
  html_document:
    code_folding: show # allows toggling of showing and hiding code. Remove if not using code.
    code_download: true # allows the user to download the source .Rmd file. Remove if not using code.
    includes:
      after_body: footer.html # include a custom footer.
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

## Day 2: Setting Up for Success

### Objectives
* Deepen an understanding of the consequences of poor data management practices [Findable]
* Review licencing of data [Reusable]
* Become familiar with  issues related to Indigenous Data Governance
* Introduce the basics of R


### Outcomes
* Identify the cascading impacts of poor RDM
* Describe basic licencing concerns and needs associated with data
* Articulate tensions between research data and the structures that surround them(policies, IP, copyright)
* Discuss Indigenous data sovereignty
* Install packages and use basic functions in R


### Deliverables
* Local root folder with appropriate directory structure created using an R script 
* An Excel and csv file of original data in appropriate directory

### Materials


### Agenda
